# Generated by Django 6.0.6 on 2026-06-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'verbose_name': 'Tarea Docente', 'verbose_name_plural': 'Tareas Docente'},
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
