# Generated by Django 6.0.6 on 2026-06-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante')], default='estudiante', max_length=20),
        ),
    ]
