# Generated by Django 6.0.6 on 2026-06-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('estudiante', 'Estudiante'), ('profesor', 'Profesor')], default='usuario', max_length=20),
        ),
    ]
