# Generated by Django 6.0.6 on 2026-06-19 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_curso_user_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='curso',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='user.role'),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
