# Generated by Django 6.0.6 on 2026-06-19 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AlterModelOptions(
            name='opcion',
            options={'verbose_name': 'Opción', 'verbose_name_plural': 'Opciones'},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='respuestacorrecta',
            options={'verbose_name': 'Respuesta Correcta', 'verbose_name_plural': 'Respuestas Correctas'},
        ),
        migrations.AlterModelOptions(
            name='respuestaestudiante',
            options={'verbose_name': 'Respuesta Estudiante', 'verbose_name_plural': 'Respuestas Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='tareas',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
    ]
